apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-discovery
spec:
  selector:
      matchLabels:
        app:  kube-discovery
  replicas: 1
  template:
    metadata:
      labels:
        app:  kube-discovery
    spec:
      containers:
        - name:  kube-discovery
          image: kube-discovery:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000