spring:
 application:
  name: discovery-server
server:
  port: 9000
  

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:9000/eureka/
  register-with-eureka: false
  fetch-registry: false